#region Copyright (c) 2023-2026 SnowBank SAS, (c) 2005-2023 Doxense SAS
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 	* Redistributions of source code must retain the above copyright
// 	  notice, this list of conditions and the following disclaimer.
// 	* Redistributions in binary form must reproduce the above copyright
// 	  notice, this list of conditions and the following disclaimer in the
// 	  documentation and/or other materials provided with the distribution.
// 	* Neither the name of SnowBank nor the
// 	  names of its contributors may be used to endorse or promote products
// 	  derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL SNOWBANK SAS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

namespace SnowBank.Testing.Framework
{
	using System.Reflection;
	using Microsoft.Extensions.FileProviders;
	using Microsoft.Extensions.Primitives;

	public sealed record DistributedComponentStaticFileProviderOptions
	{
		public string RootPath { get; set; } = "/";

		public Type? BeaconType { get; set; }

		public Assembly? BeaconAssembly { get; set; }
	}

	public class DistributedComponentStaticFileProvider : IFileProvider
	{


		public DistributedComponentStaticFileProvider(DistributedComponentStaticFileProviderOptions options)
		{
			Contract.NotNull(options);

			this.Options = options;
		}

		public DistributedComponentStaticFileProviderOptions Options { get; }

		private readonly record struct AssetInfo(string SubPath, IFileProvider Provider);

		private Dictionary<string, AssetInfo>? Assets;
		private bool Loaded;
		private object? SyncLock;

		private static class Cache
		{
			internal static readonly Dictionary<string, Dictionary<string, AssetInfo>> Items = new(StringComparer.Ordinal);
		}

		private Dictionary<string, AssetInfo> EnsureAssets()
		{
			return LazyInitializer.EnsureInitialized(ref this.Assets, ref this.Loaded, ref this.SyncLock, this.Load)!;
		}

		private Dictionary<string, AssetInfo> Load()
		{
			var assembly = this.Options.BeaconAssembly ?? this.Options.BeaconType?.Assembly;

			if (assembly == null)
			{
				// note: this may not be correct when we are running under a unit test!
				assembly = Assembly.GetExecutingAssembly();
			}

			string name = assembly.GetName().Name!;
			Dictionary<string, AssetInfo>? assets;

			// first check in the cache is we already have loaded the same exact assets in a previous run?
			var key = name + "%%" + this.Options.RootPath;
			lock (Cache.Items)
			{
				if (Cache.Items.TryGetValue(key, out assets))
				{ // use cached assets
					return assets;
				}
			}

			// Load the web assets definition JSON file.
			// This file is generated by the compiler, and describes all the static web assets that were found

			var path = Path.GetFullPath(name + ".staticwebassets.runtime.json");
			if (!File.Exists(path))
			{
				throw new InvalidOperationException($"Could not load the static web asset definition file for assembly '{name}': '{path}' not found");
			}
			var obj = CrystalJson.ParseFrom(path).AsObject();

			// create a file provider for each content root
			var contentRoots = obj.GetArray("ContentRoots");
			var providers = new IFileProvider[contentRoots.Count];
			for (int i = 0; i < contentRoots.Count; i++)
			{
				providers[i] = new PhysicalFileProvider(contentRoots.Get<string>(i));
			}

			// recursively scan each asset and its children
			assets = new Dictionary<string, AssetInfo>(StringComparer.Ordinal);

			ParseAssetNode(assets, providers, this.Options.RootPath, "Root", obj.GetObjectOrDefault("Root", null));

			// add this to the cache for the next run
			lock (Cache.Items)
			{
				Cache.Items[key] = assets;
			}

			return assets;
		}

		private static void ParseAssetNode(Dictionary<string, AssetInfo> assets, IFileProvider[] providers, string rootPath, string name, JsonObject? node)
		{
			if (node == null) return;

			// Example:

			//	"css": {
			//		"Children": {
			//			"site.css": {
			//				"Children": null,				// null for leafs (files, or folders with no files)
			//				"Asset": {						// not-null for files
			//					"ContentRootIndex": 0,		// index in the top-evel "ContentRoot" array
			//					"SubPath": "css/site.css"	// path relative to this Content Root
			//				},
			//				"Patterns": null				// unknown, it was always "null" for me
			//			}
			//		},
			//		"Asset": null,							// null for folders
			//		"Patterns": null						// unknown, it was always "null" for me
			//	},


			var asset = node.GetObjectOrDefault("Asset", null);
			if (asset != null)
			{
				var contentRootIndex = asset.Get<int>("ContentRootIndex");
				var subPath = asset.Get<string>("SubPath");
				assets.Add(rootPath + subPath, new AssetInfo(subPath, providers[contentRootIndex]));
			}

			var children = node.GetObjectOrDefault("Children", null);
			if (children != null)
			{
				foreach (var (key, child) in children)
				{
					ParseAssetNode(assets, providers, rootPath, key, child.AsObject());
				}
			}
		}


		public IDirectoryContents GetDirectoryContents(string subpath)
		{
			throw new NotSupportedException();
		}

		public IFileInfo GetFileInfo(string subpath)
		{
			var assets = EnsureAssets();

			if (!assets.TryGetValue(subpath, out var item))
			{
				return new NotFoundFileInfo(subpath);
			};

			return item.Provider.GetFileInfo(item.SubPath);
		}

		public IChangeToken Watch(string filter)
		{
			throw new NotSupportedException();
		}
	}

}
