#region Copyright (c) 2023-2026 SnowBank SAS, (c) 2005-2023 Doxense SAS
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 	* Redistributions of source code must retain the above copyright
// 	  notice, this list of conditions and the following disclaimer.
// 	* Redistributions in binary form must reproduce the above copyright
// 	  notice, this list of conditions and the following disclaimer in the
// 	  documentation and/or other materials provided with the distribution.
// 	* Neither the name of SnowBank nor the
// 	  names of its contributors may be used to endorse or promote products
// 	  derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL SNOWBANK SAS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

// the terminal APIs of Aspire are experimental: these extensions are updated with them
#pragma warning disable ASPIRETERMINAL001
#pragma warning disable ASPIRECONTAINERRUNTIME001

namespace Aspire.Hosting
{
	using System.Data.Common;
	using System.Globalization;
	using System.Reflection;
	using System.Runtime.InteropServices;
	using Aspire.Hosting.ApplicationModel;
	using Aspire.Hosting.Publishing;
	using Microsoft.Extensions.DependencyInjection;

	/// <summary>Provides extension methods that open interactive FoundationDB tools in the terminal dock of the Aspire dashboard.</summary>
	[PublicAPI]
	public static class FdbAspireTerminalExtensions
	{

		/// <summary>Name of the command that opens <c>fdbcli</c> in the terminal dock</summary>
		public const string FdbCliCommandName = "fdbcli";

		/// <summary>Name of the command that opens FdbShell in the terminal dock</summary>
		public const string FdbShellCommandName = "fdbshell";

		/// <summary>Id of the NuGet package of the FdbShell .NET tool</summary>
		public const string FdbShellPackageId = "FdbShell";

		/// <summary>Adds a command that opens <c>fdbcli</c> inside the running cluster container, in the terminal dock of the dashboard</summary>
		/// <param name="builder">Builder for the FoundationDB cluster resource</param>
		/// <returns>The same builder</returns>
		/// <remarks>
		/// <para>The command runs <c>fdbcli</c> with <c>docker exec</c> (or the configured container runtime), so the client always matches the version of the cluster.</para>
		/// <para>The command exists only in run mode. Each invocation opens a new tab in the terminal dock.</para>
		/// <para>Type <c>exit</c> before closing the tab: the container runtime can leave <c>fdbcli</c> running inside the container when the tab closes first.</para>
		/// </remarks>
		/// <example><code>builder.AddFoundationDb("fdb", apiVersion: 730, root: "/MyApp").WithFdbCli();</code></example>
		public static IResourceBuilder<FdbClusterResource> WithFdbCli(this IResourceBuilder<FdbClusterResource> builder)
		{
			Contract.NotNull(builder);

			if (!builder.ApplicationBuilder.ExecutionContext.IsRunMode)
			{
				return builder;
			}

			var resource = builder.Resource;

			return builder.WithCommand(FdbCliCommandName, "FdbCli", async context =>
			{
				if (!IsRunning(context.Services, context.ResourceName, out var snapshot))
				{
					return CommandResults.Failure("The container is not running.");
				}

				// the runtime id follows container restarts and the name suffixes generated by Aspire
				var containerId = GetContainerId(snapshot);
				if (string.IsNullOrEmpty(containerId))
				{
					return CommandResults.Failure("The container ID is not available yet.");
				}

				var runtime = await context.Services.GetRequiredService<IContainerRuntimeResolver>().ResolveAsync(context.CancellationToken).ConfigureAwait(false);

				OpenDockTerminal(context.Services, new()
				{
					Title = $"FdbCli ({resource.Name})",
					Executable = runtime.Name.ToLowerInvariant(),
					Arguments = [ "exec", "-it", containerId, "fdbcli" ],
					Placement = TerminalPlacement.Dock,
					Columns = 132,
					Rows = 40,
				});

				return CommandResults.Success();
			}, new()
			{
				Description = "Open fdbcli inside the running container, in the terminal dock.",
				IconName = "WindowConsole",
				UpdateState = context => context.ResourceSnapshot.State?.Text == KnownResourceStates.Running && !string.IsNullOrEmpty(GetContainerId(context.ResourceSnapshot))
					? ResourceCommandState.Enabled
					: ResourceCommandState.Disabled,
			});
		}

		/// <summary>Adds a command that opens FdbShell, connected to this cluster, in the terminal dock of the dashboard</summary>
		/// <param name="builder">Builder for the FoundationDB cluster resource</param>
		/// <returns>The same builder</returns>
		/// <exception cref="DistributedApplicationException">In run mode, the AppHost does not reference the <c>FoundationDB.Client.Native</c> package, or references the package of another major.minor version than the cluster.</exception>
		/// <remarks>
		/// <para>The command runs the <c>FdbShell</c> .NET tool from NuGet with <c>dotnet tool exec</c>: the first run downloads the package, later runs start from the NuGet cache.
		/// The package sources come from the <c>nuget.config</c> of the AppHost directory, and the AppHost needs no reference to the tool.
		/// The command runs the <c>FdbShell</c> released with this package, of the same version: the tool and the AppHost always agree on the <c>--aspire</c> contract, whatever newer versions of the tool exist.</para>
		/// <para>The AppHost project must reference the <c>FoundationDB.Client.Native</c> package of the branch of the cluster, as the applications do (ex: the 7.3.x package for a 7.3.x cluster).
		/// FdbShell loads the native client of that package from the output folder of the AppHost, so it talks to the cluster with the same client as the applications.
		/// In run mode, this method throws when that package is missing, or belongs to another major.minor version than <see cref="FdbClusterResource.ClusterVersion"/>, so the AppHost stops at startup with the fix in the message.</para>
		/// <para>FdbShell receives the connection string of the cluster in <c>ConnectionStrings__{name}</c>, as any process that references the cluster, and starts with <c>--aspire {name}</c>.
		/// It opens the whole database, and starts in the <see cref="FdbClusterResource.Root"/> folder of the applications.</para>
		/// <para>The command exists only in run mode. Each invocation opens a new tab in the terminal dock.</para>
		/// </remarks>
		/// <example><code>builder.AddFoundationDb("fdb", apiVersion: 740, root: "/MyApp").WithFdbShell();</code></example>
		public static IResourceBuilder<FdbClusterResource> WithFdbShell(this IResourceBuilder<FdbClusterResource> builder)
		{
			Contract.NotNull(builder);

			if (!builder.ApplicationBuilder.ExecutionContext.IsRunMode)
			{
				return builder;
			}

			var resource = builder.Resource;
			var version = GetPackageVersion();
			var appHostDirectory = builder.ApplicationBuilder.AppHostDirectory;
			var nativeLibraryPath = FindNativeLibrary(resource, required: true);

			return AddFdbShellCommand(builder, nativeLibraryPath, (title) => new()
			{
				Title = title,
				Executable = "dotnet",
				// the tool targets a specific runtime, roll forward when only a newer one is installed
				Arguments = [ "tool", "exec", FdbShellPackageId + "@" + version, "--allow-roll-forward", "--", "--aspire", resource.Name ],
				WorkingDirectory = appHostDirectory,
			});
		}

		/// <summary>Finds the native client that the <c>FoundationDB.Client.Native</c> package copied into the output folder of the AppHost, and checks that it matches the branch of the cluster</summary>
		/// <param name="resource">The FoundationDB cluster resource</param>
		/// <param name="required">If <c>true</c>, the AppHost must reference the package; if <c>false</c>, a missing package returns <c>null</c></param>
		/// <returns>Full path of the native library, or <c>null</c> if the AppHost does not reference the package and <paramref name="required"/> is <c>false</c></returns>
		/// <exception cref="DistributedApplicationException">The AppHost does not reference the package while <paramref name="required"/> is <c>true</c>, or references the package of another branch.</exception>
		private static string? FindNativeLibrary(FdbClusterResource resource, bool required)
		{
			var cluster = resource.ClusterVersion;
			var branch = cluster.Major.ToString(CultureInfo.InvariantCulture) + "." + cluster.Minor.ToString(CultureInfo.InvariantCulture);
			string fix = $"Add <PackageReference Include=\"FoundationDB.Client.Native\" Version=\"{branch}.*\" /> to the AppHost project, the same package as the applications that use the '{resource.Name}' cluster.";

			// the managed assembly of the package carries the native version (ex: 7.3.78.0 for the 7.3.78 package)
			var assemblyPath = Path.Combine(AppContext.BaseDirectory, "FoundationDB.Client.Native.dll");
			if (!File.Exists(assemblyPath))
			{
				if (!required)
				{
					return null;
				}
				throw new DistributedApplicationException($"WithFdbShell() needs the native FoundationDB client of the '{resource.Name}' cluster ({cluster}), but the AppHost does not reference the FoundationDB.Client.Native package. {fix}");
			}

			var native = AssemblyName.GetAssemblyName(assemblyPath).Version;
			if (native == null || native.Major != cluster.Major || native.Minor != cluster.Minor)
			{
				throw new DistributedApplicationException($"WithFdbShell() needs the native FoundationDB client of the '{resource.Name}' cluster ({cluster}), but the AppHost references the FoundationDB.Client.Native package {native?.ToString(3) ?? "of unknown version"}, which cannot connect to a {branch} cluster. {fix}");
			}

			// same probing as UseNativeClient(): under runtimes/{rid}/native/ for a portable build, or next to the executable for a build of a specific runtime
			string fileName = OperatingSystem.IsWindows() ? "fdb_c.dll" : OperatingSystem.IsMacOS() ? "libfdb_c.dylib" : "libfdb_c.so";
			string rid = (OperatingSystem.IsWindows() ? "win" : OperatingSystem.IsMacOS() ? "osx" : "linux") + "-" + RuntimeInformation.OSArchitecture.ToString().ToLowerInvariant();
			string[] candidates = [ Path.Combine(AppContext.BaseDirectory, "runtimes", rid, "native", fileName), Path.Combine(AppContext.BaseDirectory, fileName) ];
			return candidates.FirstOrDefault(File.Exists)
				?? throw new DistributedApplicationException($"WithFdbShell() found the FoundationDB.Client.Native package {native.ToString(3)} in the AppHost, but not its native library for the '{rid}' platform (probed: {string.Join(", ", candidates)}).");
		}

		/// <summary>Adds a command that opens FdbShell, built from source, connected to this cluster, in the terminal dock of the dashboard</summary>
		/// <typeparam name="TProject">Project metadata of FdbShell, generated by a <c>ProjectReference</c> of the AppHost to <c>FdbShell.csproj</c></typeparam>
		/// <param name="builder">Builder for the FoundationDB cluster resource</param>
		/// <param name="targetFramework">Target framework of the FdbShell build to run (ex: <c>"net10.0"</c>), or <c>null</c> for the framework of the AppHost</param>
		/// <returns>The same builder</returns>
		/// <remarks>
		/// <para>Use this overload in a solution that holds the source of FdbShell. Applications that consume the NuGet packages use <see cref="WithFdbShell(IResourceBuilder{FdbClusterResource})"/> instead.</para>
		/// <para>FdbShell loads its own native client, or the one of the <c>FoundationDB.Client.Native</c> package when the AppHost references it. In run mode, this method throws when that package belongs to another major.minor version than <see cref="FdbClusterResource.ClusterVersion"/>.</para>
		/// <para>The command runs FdbShell on the host with <c>dotnet run --no-build</c>: the AppHost build must also build FdbShell for <paramref name="targetFramework"/>.
		/// FdbShell multi-targets, so the <c>ProjectReference</c> of the AppHost should pin a single framework with <c>SetTargetFramework</c>.</para>
		/// <para>FdbShell receives the connection string of the cluster in <c>ConnectionStrings__{name}</c>, as any process that references the cluster, and starts with <c>--aspire {name}</c>.
		/// It opens the whole database, and starts in the <see cref="FdbClusterResource.Root"/> folder of the applications.</para>
		/// <para>The command exists only in run mode. Each invocation opens a new tab in the terminal dock.</para>
		/// </remarks>
		/// <example><code>builder.AddFoundationDb("fdb", apiVersion: 740, root: "/MyApp").WithFdbShell&lt;Projects.FdbShell&gt;();</code></example>
		public static IResourceBuilder<FdbClusterResource> WithFdbShell<TProject>(this IResourceBuilder<FdbClusterResource> builder, string? targetFramework = null)
			where TProject : IProjectMetadata, new()
		{
			Contract.NotNull(builder);

			var resource = builder.Resource;
			var projectPath = new TProject().ProjectPath;
			// FdbShell built from source loads its own native client, unless the AppHost references the FoundationDB.Client.Native package
			var nativeLibraryPath = builder.ApplicationBuilder.ExecutionContext.IsRunMode ? FindNativeLibrary(resource, required: false) : null;
			targetFramework ??= "net" + Environment.Version.Major.ToString(CultureInfo.InvariantCulture) + ".0";
			// run the same configuration as the AppHost, which built FdbShell through its ProjectReference
			var configuration = Assembly.GetEntryAssembly()?.GetCustomAttribute<AssemblyConfigurationAttribute>()?.Configuration is { Length: > 0 } config ? config : "Debug";

			return AddFdbShellCommand(builder, nativeLibraryPath, (title) => new()
			{
				Title = title,
				Executable = "dotnet",
				Arguments = [ "run", "--project", projectPath, "--no-build", "--no-launch-profile", "--configuration", configuration, "--framework", targetFramework, "--", "--aspire", resource.Name ],
				WorkingDirectory = Path.GetDirectoryName(projectPath),
			});
		}

		/// <summary>Adds the FdbShell command, which runs the process described by <paramref name="createOptions"/> in a new tab of the terminal dock</summary>
		/// <param name="builder">Builder for the FoundationDB cluster resource</param>
		/// <param name="nativeLibraryPath">If not <c>null</c>, path of the native client that FdbShell must load, instead of its own</param>
		/// <param name="createOptions">Creates the launch options of the process, given the title of its tab</param>
		private static IResourceBuilder<FdbClusterResource> AddFdbShellCommand(IResourceBuilder<FdbClusterResource> builder, string? nativeLibraryPath, Func<string, TerminalLaunchOptions> createOptions)
		{
			if (!builder.ApplicationBuilder.ExecutionContext.IsRunMode)
			{
				return builder;
			}

			var resource = builder.Resource;

			return builder.WithCommand(FdbShellCommandName, "FdbShell", async context =>
			{
				if (!IsRunning(context.Services, context.ResourceName, out _))
				{
					return CommandResults.Failure("The cluster is not running.");
				}

				var connectionString = await resource.ConnectionStringExpression.GetValueAsync(context.CancellationToken).ConfigureAwait(false);
				if (string.IsNullOrEmpty(connectionString))
				{
					return CommandResults.Failure("The connection string of the cluster is not available yet.");
				}

				var options = createOptions($"FdbShell ({resource.Name})");
				options.Placement = TerminalPlacement.Dock;
				options.Columns = 160;
				options.Rows = 48;
				if (nativeLibraryPath != null)
				{ // only the copy given to FdbShell names the library: the applications keep loading their own native client
					connectionString = new DbConnectionStringBuilder() { ConnectionString = connectionString, ["NativeLibrary"] = nativeLibraryPath }.ConnectionString;
				}
				options.EnvironmentVariables["ConnectionStrings__" + resource.Name] = connectionString;

				OpenDockTerminal(context.Services, options);

				return CommandResults.Success();
			}, new()
			{
				Description = "Open FdbShell, connected to this cluster, in the terminal dock.",
				IconName = "WindowConsole",
				UpdateState = context => context.ResourceSnapshot.State?.Text == KnownResourceStates.Running
					? ResourceCommandState.Enabled
					: ResourceCommandState.Disabled,
			});
		}

		/// <summary>Returns the NuGet version of this package (ex: <c>"7.4.8"</c>, or <c>"7.4.8-rc1"</c>), which is also the version of the <c>FdbShell</c> tool released with it</summary>
		private static string GetPackageVersion()
		{
			var assembly = typeof(FdbAspireTerminalExtensions).Assembly;
			// the informational version is the package version, followed by "+{commit}" when built from a git repository
			var informational = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
			if (!string.IsNullOrEmpty(informational))
			{
				int p = informational.IndexOf('+');
				return p < 0 ? informational : informational.Substring(0, p);
			}
			return assembly.GetName().Version?.ToString(3) ?? throw new InvalidOperationException("The version of the FoundationDB.Aspire.Hosting assembly is not available.");
		}

		private static void OpenDockTerminal(IServiceProvider services, TerminalLaunchOptions options)
		{
			// dock terminals outlive the command: the dashboard disposes them when the tab closes, or when the AppHost stops
			var terminal = services.GetRequiredService<TerminalService>().CreateTerminal(options);
			terminal.Start();
			terminal.Show();
		}

		private static bool IsRunning(IServiceProvider services, string resourceName, out CustomResourceSnapshot snapshot)
		{
			if (services.GetRequiredService<ResourceNotificationService>().TryGetCurrentState(resourceName, out var evt) && evt.Snapshot.State?.Text == KnownResourceStates.Running)
			{
				snapshot = evt.Snapshot;
				return true;
			}
			snapshot = null!;
			return false;
		}

		private static string? GetContainerId(CustomResourceSnapshot snapshot)
			=> snapshot.Properties.FirstOrDefault(p => p.Name == "container.id")?.Value as string;

	}

}
