#region Copyright (c) 2023-2026 SnowBank SAS, (c) 2005-2023 Doxense SAS
// All rights reserved.
// 
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
// 	* Redistributions of source code must retain the above copyright
// 	  notice, this list of conditions and the following disclaimer.
// 	* Redistributions in binary form must reproduce the above copyright
// 	  notice, this list of conditions and the following disclaimer in the
// 	  documentation and/or other materials provided with the distribution.
// 	* Neither the name of SnowBank nor the
// 	  names of its contributors may be used to endorse or promote products
// 	  derived from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL SNOWBANK SAS BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
// ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#endregion

namespace SnowBank.Networking.PacketCapture
{
	using System.Globalization;
	using System.Text;
	using Microsoft.Net.Http.Headers;
	using SnowBank.Text;

	/// <summary>Holds all the information of a captured packet.</summary>
	[DebuggerDisplay("Id={Id}, Req=[{Metadata.Request.Method} {Metadata.Request.Path}], Res=[{Metadata.Response.Status} {Metadata.Response.ReasonPhrase}]")]
	[PublicAPI]
	public sealed record CapturedPacket
	{

		/// <summary>Local ID of the packet in the store</summary>
		/// <remarks>
		/// This is an artificial ID that is used by the store to enable log streaming to clients (using cursors).
		/// The ID is only guaranteed to be unique in time, but not in space (ie: only unique in the context of the same store).
		/// ID are generated by the packet capture manager, and assigned when then are picked from the queue (ie: ordered by EMIT time, not by the START of the request!)
		/// </remarks>
		[JsonProperty("id")]
		public required CapturedPacketId Id { get; init; }

		/// <summary>Metadata of the packet (uri, method, request and response headers, ...)</summary>
		[JsonProperty("metadata")]
		public required CapturedPacketMetadata Metadata { get; init; }

		/// <summary>Holds the body of the request (if there was one, and if it was captured)</summary>
		[JsonProperty("requestBody")]
		public required Slice RequestBody { get; init; }

		/// <summary>Holds the body of the response (if there was one, and if it was captured)</summary>
		[JsonProperty("responseBody")]
		public required Slice ResponseBody { get; init; }

		private static bool IsProbablyText(MediaTypeHeaderValue? mediaType)
		{
			if (mediaType == null) return true; // tentes ta chance!
			if (mediaType.Type == "text") return true;
			if (mediaType.Type == "image") return false;
			if (mediaType.Type == "application")
			{
				if (mediaType.SubType == "json") return true;
				if (mediaType.SubType == "x-www-form-urlencoded") return true;
			}
			return false;
		}

		public async Task DumpRequestTo(Stream output, StringBuilder cache, CancellationToken ct)
		{
			var fields = this.Metadata.Fields;
			var request = this.Metadata.Request;

			cache.Clear();
			cache.Append(request.Method ?? "???").Append(' ');
			if (!string.IsNullOrEmpty(request.QueryString))
			{
				cache.Append(request.Path ?? "/* path not captured*/").Append('?').AppendLine(request.QueryString);
			}
			else
			{
				cache.AppendLine(request.Path ?? "/* path not captured */");
			}
			if (fields.HasFlag(CapturedHttpFields.RequestHeaders))
			{
				foreach (var (name, value) in request.Headers)
				{
					cache.AppendLine($"{name}: {value}");
				}
			}
			else
			{
				cache.AppendLine("/* headers not captured */");
			}
			cache.AppendLine();

			await output.WriteAsync(Encoding.UTF8.GetBytes(cache.ToString()), ct);
			if (request.HasBody && fields.HasFlag(CapturedHttpFields.RequestBody))
			{
				await output.WriteAsync(this.RequestBody.Memory, ct);
			}
		}

		public async Task DumpResponseTo(Stream output, StringBuilder cache, CancellationToken ct)
		{
			var fields = this.Metadata.Fields;
			var response = this.Metadata.Response;

			cache.Clear();
			cache.Append(response.Status).Append(' ').AppendLine(response.ReasonPhrase);
		
			if (fields.HasFlag(CapturedHttpFields.ResponseHeaders))
			{
				foreach (var (name, value) in response.Headers)
				{
					cache.AppendLine($"{name}: {value}");
				}
			}
			else
			{
				cache.AppendLine("/* headers not captured */");
			}
			cache.AppendLine();

			await output.WriteAsync(Encoding.UTF8.GetBytes(cache.ToString()), ct);
			if (response.HasBody && fields.HasFlag(CapturedHttpFields.ResponseBody))
			{
				await output.WriteAsync(this.ResponseBody.Memory, ct);
			}
		}

		public string GetBasicDump(bool includeBody = true)
		{
			var metadata = this.Metadata;
			var fields = metadata.Fields;
			var request = metadata.Request;
			var response = metadata.Response;

			var sb = StringBuilderCache.Acquire(128);
			sb.AppendLineInvariant($"# Captured Packet: {this.Id} from {metadata.Connection.RemoteHost} [{metadata.TraceId}]");
			sb.AppendLineInvariant($"# Started  : {metadata.StartedAt:yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff}");
			sb.AppendLineInvariant($"# Connection: {metadata.Connection.Id}, {metadata.Connection.RemoteHost}:{metadata.Connection.RemotePort}");
			if (metadata.ProcessedAt != null)
			{
				sb.AppendLineInvariant($"# Processed: {metadata.ProcessedAt.Value:yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff} ({(metadata.ProcessedAt.Value - metadata.StartedAt).ToTimeSpan().TotalMilliseconds:N3} ms)");
			}
			if (metadata.EndedAt != null)
			{
				sb.AppendLineInvariant($"# Completed: {metadata.EndedAt.Value:yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffff} ({(metadata.EndedAt.Value - metadata.StartedAt).ToTimeSpan().TotalMilliseconds:N3} ms)");
			}

			sb.AppendLine("## REQUEST:");
			sb.Append(request.Method).Append(' ').Append(request.Path).AppendLine();
			if (fields.HasFlag(CapturedHttpFields.RequestHeaders))
			{
				foreach (var (name, value) in request.Headers)
				{
					sb.AppendLineInvariant($"{name}: {value}");
				}
			}
			sb.AppendLine();
			if (includeBody && request.HasBody)
			{
				if (/*this.Request.Headers.Headers["Content-Encoding"].Count == 0 &&*/ IsProbablyText(request.GetTypedHeaders().ContentType))
				{
					//BUGBUG: encoding?
					sb.AppendLine(this.RequestBody.ToStringUtf8());
				}
				else
				{
					sb.Append(HexaDump.Format(this.RequestBody)).AppendLine();
				}
			}

			sb.AppendLine();
			sb.AppendLine("## RESPONSE:");
			if (response.Status != 0)
			{
				sb.Append(response.Status).Append(' ').Append(response.ReasonPhrase).AppendLine();
				sb.AppendLine();
				if (fields.HasFlag(CapturedHttpFields.ResponseHeaders))
				{
					foreach (var x in response.Headers)
					{
						sb.AppendLineInvariant($"{x.Key}: {x.Value}");
					}
				}

				sb.AppendLine();
				if (includeBody && response.HasBody)
				{
					if ( /*this.Response.Headers.Headers["Content-Encoding"].Count == 0 &&*/ IsProbablyText(response.GetTypedHeaders().ContentType))
					{
						//BUGBUG: encoding?
						sb.AppendLine(this.ResponseBody.ToStringUtf8());
					}
					else
					{
						sb.Append(HexaDump.Format(this.ResponseBody)).AppendLine();
					}
				}
			}
			else
			{
				sb.AppendLine("# <missing>");
			}

			sb.AppendLine("# End of Packet");

			return sb.ToString();
		}

		private const string LOG_TOKEN_EMPTY = "- ";

		internal static StringBuilder LogAppendNumber(StringBuilder sb, double? value, string format, int padding)
		{
			if (value.HasValue)
			{
				return AppendRightAligned(sb, value.Value.ToString(format), padding).Append(' ');
			}
			else
			{
				return sb.Append(LOG_TOKEN_EMPTY);
			}
		}

		internal static StringBuilder LogAppendNumber(StringBuilder sb, long? value, string format, int padding)
		{
			if (value.HasValue)
			{
				return AppendRightAligned(sb, value.Value.ToString(format), padding).Append(' ');
			}
			else
			{
				return sb.Append(LOG_TOKEN_EMPTY);
			}
		}

		private static StringBuilder AppendRightAligned(StringBuilder sb, string text, int padding)
		{
			return text.Length < padding ? sb.Append(' ', padding - text.Length).Append(text) : sb.Append(text);
		}

		/// <summary>Encode une chaîne de texte au format W3C LOG</summary>
		private static void LogAppendString(StringBuilder sb, string? text, bool quoted)
		{
			// <string> = '"' *<schar> '"'
			// <schar>  = xchar | '"' '"'
			// Strings are output in quoted form. If a string contains a quotation character the character is repeated. This format is unambiguous since fields are by definition separated by whitespace. The dash character must not be used as an abbreviation for an empty string.
			// No mechanism for incorporating control characters is defined.

			if (string.IsNullOrEmpty(text))
			{
				// EXCEPTION: "The dash character must not be used as an abbreviation for an empty string."
				// ... sauf que beaucoup headers property retournent "" même s'ils sont manquants
				sb.Append(LOG_TOKEN_EMPTY);
				return;
			}

			if (quoted) sb.Append('"');
			foreach (var c in text)
			{
				if (c < 32 || c > 255)
				{ // Replace non-printable characters by '+'
					sb.Append('?');
				}
				else if (c == ' ')
				{
					sb.Append(quoted ? ' ' : '+');
				}
				else if (c == '"')
				{
					sb.Append("\"\"");
				}
				else
				{
					sb.Append(c);
				}
			}
			if (quoted) sb.Append("\" "); else sb.Append(' ');
		}

		public string ToSingleLineLog()
		{
			var cnx = this.Metadata.Connection;
			var request = this.Metadata.Request;
			var response = this.Metadata.Response;

			int status = response.Status;
			var date = cnx.StartedAt.ToDateTimeOffset().LocalDateTime;
			var durationTotal = this.Metadata.EndedAt != null ? (this.Metadata.EndedAt.Value - this.Metadata.StartedAt).ToTimeSpan() : TimeSpan.Zero;

			var sb = StringBuilderCache.Acquire(128);

			// date
			sb.Append(date.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture)).Append(' ');
			// time
			sb.Append(date.ToString("HH:mm:ss.fff", CultureInfo.InvariantCulture)).Append(' ');
			// x-cnx-id : identifiant unique de la connexion
			LogAppendString(sb, cnx.Id, false);
			// x-cnx-req: '-' pour première execution pour cette connection, ou nombre de réutilisations de la connection
			sb.Append(" - "); //TODO: how can we get this value?

			// ### Result

			// cs-bytes : octets envoyés par le client, incluant les headers et le body de la requête
			LogAppendNumber(sb, this.RequestBody.Count, "N0", 7);
			// time-taken : nombre de millisecondes écoulées pour traiter la requête de bout en bout
			LogAppendNumber(sb, durationTotal.TotalMilliseconds, "N1", 7).Append(' ');
			// sc-bytes : octets envoyés par le serveur, incluant les headers et le body de la réponse
			LogAppendNumber(sb, this.ResponseBody.Count, "N0", 7);

			// sc-status
			if (status == 0) sb.Append("--- "); else sb.Append(status).Append(' ');

			// ### Request

			// cs-method : "GET", "POST", ...
			AppendRightAligned(sb, request.Method ?? "????", 4).Append(' ');
			// cs-uri-stem : "/path/to/page.html"
			sb.Append(request.Path ?? "-").Append(' ');
			// cs-uri-query : "foo=123&bar=456&isadmin=true"
			LogAppendString(sb, request.QueryString, false);

			// cs(Content-Type) : Content-Type of the request body (POST, PUT, PATCH, ...), AFTER decompression
			LogAppendString(sb, request.Headers.ContentType, true);
			// cs(Content-Length) : Length of the request body (POST, PUT, PATCH, ...)
			LogAppendNumber(sb, request.Headers.ContentLength, "N0", 7);

			// ### Response

			// sc(Content-Type) : Content-Type of the response body (GET, POST, ...)
			LogAppendString(sb, response.Headers.ContentType, true);
			// cs(User-Agent)
			LogAppendString(sb, request.Headers.UserAgent, true);

			// we need to remove the trailing space that is always added by LogAppendString(...)
			sb.Length -= 1;

			return StringBuilderCache.GetStringAndRelease(sb);
		}

		public override string ToString()
		{
			var req = this.Metadata.Request;
			Contract.Debug.Assert(req != null && req.Headers != null);
			var res = this.Metadata.Response;
			Contract.Debug.Assert(res != null);
			return $"{req.Method} {this.Metadata.Uri} [{req.Headers.ContentType}] {(req.HasBody ? $"{this.RequestBody.Count:N0} bytes": "<no body>")} => {res.Status} {res.ReasonPhrase} [{res.Headers.ContentType}] {(res.HasBody ? $"{this.ResponseBody.Count:N0} bytes": "<no body>")}";
		}

	}

}
