<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFrameworks>$(CoreSdkRuntimeVersions)</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<IsTestProject>true</IsTestProject>
		<IsPackable>false</IsPackable>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<SignAssembly>true</SignAssembly>
		<DelaySign>false</DelaySign>
		<RunAnalyzersDuringBuild>false</RunAnalyzersDuringBuild>
	</PropertyGroup>

	<Import Project="..\..\VersionInfo.props" />

	<PropertyGroup>
		<ServerGarbageCollection>true</ServerGarbageCollection>
		<ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
		<DisableImplicitFrameworkReferences>false</DisableImplicitFrameworkReferences>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="NUnit" />
		<PackageReference Include="NUnit.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NUnit3TestAdapter">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SnowBank.Testing.Common\SnowBank.Testing.Common.csproj" />
		<ProjectReference Include="..\FoundationDB.FakeDb\FoundationDB.FakeDb.csproj" />
	</ItemGroup>

</Project>
