name: Pack Native Clients

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the binaries ("latest" or "7.3.52")'
        required: true
        default: 'latest'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install .NET SDK
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: 11.0.100-preview.7.26381.103
        dotnet-quality: 'preview'
    - name: Download Binaries
      shell: pwsh
      run: |
        cd FoundationDB.Client.Native
        ./DownloadBinaries.ps1 `
          -version "${{ github.event.inputs.version }}" `
          -manifestPath "./manifest.json" `
          -outputDir "."
    - name: NuGet Pack
      env:
        DISABLE_NATIVE_PACKAGE: false
      run: dotnet pack ./FoundationDB.Client.Native/FoundationDB.Client.Native.csproj -c Release --output Redist
    - name: Upload artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: NuGet Packages
        path: |
          Redist/*.nupkg
          Redist/*.snupkg
        if-no-files-found: error
