name: .NET Build

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:

    # checkout code from repository
    - name: Checkout repository
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

    # install the latest .NET SDK on the local worker
    - name: Install .NET SDK
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
      with:
        dotnet-version: 10.0.100
        #dotnet-quality: 'preview'

    # build the solution (Release)
    - name: Restore
      run: dotnet restore


    # build the solution (Release)
    - name: Build (Release)
      run: dotnet build -c Release --no-restore -nowarn:CS1591

    # Pack the libraries and tools
    - name: NuGet Pack
      env:
        DISABLE_NATIVE_PACKAGE: true
      run: dotnet pack -c Release --no-restore --no-build --output Redist -p:ContinuousIntegrationBuild=true

    # Capture the build packages
    - name: Upload artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: NuGet Packages
        path: |
          Redist/*.nupkg
          Redist/*.snupkg
        if-no-files-found: error

    # In case of error, we want to capture any generated file for troubleshooting
    - name: Capture generated source files
      if: failure()  
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: Generated Source Files
        path: '**/*.g.cs' 
